name: Sync Authentik Image to Docker Hub

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"

jobs:
  sync:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: ghcr.io/goauthentik/server
      TARGET_IMAGE: ${{ secrets.DOCKERHUB_USERNAME }}/authentik

    steps:
      - name: Get latest Authentik tag
        id: tag
        run: |
          TAG=$(curl -s https://ghcr.io/v2/goauthentik/server/tags/list | \
            jq -r '.tags[]' | \
            grep -E '^[0-9]+\.[0-9]+(\.[0-9]+)?$' | \
            sort -V | \
            tail -n1)

          echo "tag=$TAG" >> $GITHUB_OUTPUT
          echo "Latest tag: $TAG"

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Pull image
        run: |
          docker pull ${IMAGE_NAME}:${{ steps.tag.outputs.tag }}

      - name: Tag image
        run: |
          docker tag \
            ${IMAGE_NAME}:${{ steps.tag.outputs.tag }} \
            ${TARGET_IMAGE}:${{ steps.tag.outputs.tag }}

          docker tag \
            ${IMAGE_NAME}:${{ steps.tag.outputs.tag }} \
            ${TARGET_IMAGE}:latest

      - name: Push image
        run: |
          docker push ${TARGET_IMAGE}:${{ steps.tag.outputs.tag }}
          docker push ${TARGET_IMAGE}:latest
