name: Transfer Authentik to Docker Hub

on:
  workflow_dispatch: # امکان اجرای دستی ورک‌فلو را فراهم می‌کند
  schedule:
    - cron: '0 0 * * 0' # اجرای خودکار هر هفته (اختیاری)

jobs:
  transfer-image:
    runs-on: ubuntu-latest

    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Pull Authentik Image from GHCR
        run: docker pull ghcr.io/goauthentik/server:latest

      - name: Tag Image for Docker Hub
        run: docker tag ghcr.io/goauthentik/server:latest ${{ secrets.DOCKER_USERNAME }}/authentik:latest

      - name: Push Image to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/authentik:latest
