name: Check New Courses

on:
  schedule:
    - cron: '0 */6 * * *' # هر ۶ ساعت یک‌بار اجرا می‌شود
  workflow_dispatch: # امکان اجرای دستی را هم به شما می‌دهد

jobs:
  check-rss:
    runs-on: ubuntu-latest
    permissions:
      contents: write # برای آپدیت کردن فایل متنی نیاز است

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run checker script
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python main.py

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add last_course.txt
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update last course link" && git push)
